name: mirror-to-publishdata
on: [push]
concurrency:
  group: mirror-to-publishdata
jobs:
  mirror-to-publishdata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git config --global user.email ${{ github.event.pusher.email }}
      - run: git clone --bare git@github.com:surh/Rmarkdown_workshop
