name: mirror-to-publishdata
on: [push]
concurrency:
  group: mirror-to-publishdata
jobs:
  mirror-to-publishdata:
    runs-on: ubuntu-latest
    steps:
      - name: Config git for GitHub
        run: |
           git config --global user.email ${{ github.event.pusher.email }}
           git config --global user.name ${{ github.event.pusher.name }}
      - name: set SSH for source
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: clone source
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: git clone --bare git@github.com:surh/Rmarkdown_workshop ./
      - name: set SSH for mirror
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent2.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_MIRROR_PRIVATE_KEY }}"
      - name: push to mirror
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent2.sock
        run: git push --mirror git@github.com:publishdata/Rmarkdown_workshop
