name: mirror-to-publishdata
on: [push]
concurrency:
  group: mirror-to-publishdata
jobs:
  mirror-to-publishdata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: git config --global user.email ${{ github.event.pusher.email }}
      - run: mkdir ~/.ssh
      - run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
      - run: chmod 400 ~/.ssh/id_rsa
      # - run: eval "$(ssh-agent -s)"
      # - run: ssh-add key
      # - run: ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
      # - run: export GIT_SSH_PRIVATE_KEY="${{ secrets.SSH_PRIVATE_KEY }}"
      - run: git clone --bare git@github.com:surh/Rmarkdown_workshop
