name: mirror-to-publishdata
on: [push]
concurrency:
  group: mirror-to-publishdata
jobs:
  mirror-to-publishdata:
    runs-on: ubuntu-latest
    - env:
      EMAIL: ${{ github.event.pusher.email }}
    steps:
      - uses: actions/checkout@v3
